### ISSUE TITLE
When will you upload the code and instruction guidelines?

### ISSUE THREAD

**Issue by janesunflower** [prgumd/EVDodgeNet#1]

**Comment by apple1987** [comment]
The same question as you~

**Comment by NitinJSanket** [comment]
The dataset is now released in parts here: https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python
You can also find the tentative release dates for other parts here: https://github.com/prgumd/EVDodgeNet/wiki
