### ISSUE TITLE
Require your dataset and code

### ISSUE THREAD

**Issue by hamidehkerdegari** [prgumd/EVDodgeNet#2]
Hello,

I need your dataset and code to compare your paper with my work. When will you release them?
Thanks.

**Comment by NitinJSanket** [comment]
The dataset is now released in parts here: https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python
You can also find the tentative release dates for other parts here: https://github.com/prgumd/EVDodgeNet/wiki

**Comment by Ethan-Zhou** [comment]
Hi @NitinJSanket ,

Thanks for your release. I am downloading the dataset. However, as far as I see, the data structure is not very well organized, not the same as shown in https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python.
I download the data from the goolge drive link you provided (https://drive.google.com/drive/folders/1pJSVXtRlTU4_b-I8oakoZtl1ChcG0OiQ). I right click on the Text_images, and choose download. Then it takes quite a while for zipping. Once the zipping job is finished, a number of window comes out asking me to save them as several independent files. I don't know if I was doing that correctly.
Any, it would be appreaciated if you can make the dataset download much easier.

Cheers,

yi

**Comment by Ethan-Zhou** [comment]
Hi @NitinJSanket,
Following the above message, I am reporting what I see after downloading "everything" from Test_images folder at https://drive.google.com/drive/folders/1pJSVXtRlTU4_b-I8oakoZtl1ChcG0OiQ.
Still, the data structure is not identical as you mentioned. Corresonding event.txt files are missing almost everywhere. Some other files (cases are different in each sequence) are also not available. I hope you can revise this data release, such that more researchers would find this useful.
Cheers,
yi

**Comment by NitinJSanket** [comment]
@Ethan-Zhou I'll have a look at this and will get back to you after 31st October.

**Comment by Ethan-Zhou** [comment]
Hi @NitinJSanket,

I am sorry for the last report. It seems that the goolge drive was somehow not doing the job correctly. Now I can see the exactly the same data structure as you described at https://github.com/prgumd/EVDodgeNet/wiki/Access-Data-Set-Using-ROS-Python. Thanks for your effort again.

Cheers,

yi

**Comment by Ethan-Zhou** [comment]
Hi @NitinJSanket,
I have checked the event.txt under test_seq folder. It seems that events after 3 seconds are missing. Images and other data stop by 4 sec.

**Comment by chethanparameshwara** [comment]
Hi @Ethan-Zhou,

Thanks for informing us. Updated the files with 5 sec data.
