### ISSUE TITLE
Segmentation network syntax error

### ISSUE THREAD

**Issue by ercanburak** [prgumd/EVDodgeNet#3]
Hello, thanks for your work.

I am trying to use the EVSegNet code you provided. There is a syntax error in the following part of the code: https://github.com/prgumd/EVDodgeNet/blob/0b6f6a0fc781203d3bc395c5305ff7c7ffc7535e/code/EVSegNet/RunEVSegNet.py#L280-L283. 

Specifically, lines 281 and 282 should be switched.

**Comment by chethanparameshwara** [comment]
resolved in https://github.com/prgumd/EVDodgeNet/pull/7
