### ISSUE TITLE
Segmentation network name error

### ISSUE THREAD

**Issue by ercanburak** [prgumd/EVDodgeNet#4]
Hello. The following code line: 

https://github.com/prgumd/EVDodgeNet/blob/0b6f6a0fc781203d3bc395c5305ff7c7ffc7535e/code/EVSegNet/RunEVSegNet.py#L291

produces a "NameError" since "global name 'tu' is not defined".

**Comment by chethanparameshwara** [comment]
resolved in https://github.com/prgumd/EVDodgeNet/pull/7
