### ISSUE TITLE
WIKI

### ISSUE THREAD

**Issue by aahuhu** [prgumd/EVDodgeNet#8]
There is something wrong in the dataset you supplied , because there is no downfacing rosbag .what's more, could you tell me the input and output of deblurnet and homography net.I can not understand the wiki instruction.

**Comment by NitinJSanket** [comment]
Hi, 
You're right, the down-facing images are missing. (We'll try to get that soon). Meanwhile, if you want to run the deblurnet and homography net, you can run them directly on the front facing images. 

To run deblurnet: Please go to `code\DeblurNetUnsup\`  then run `RunEVDeblurNet.py` with the appropriate command line flags . The command would be:
`RunEVDeblurNet.py --ModelPath=YOURMODELPATH --ReadPath=YOURPATHTOFRONTORDOWNIMGS --WritePath=PATHTOSAVEOUTPUTS`

For e.g.,
 `RunEVDeblurNet.py --ModelPath=/media/nitin/Research/EVDodge/CheckpointsDeblurNetLR1e-4GradAndPhoto/399model.ckpt--ReadPath=/media/nitin/Research/EVDodge/DatasetChethanEvents/processed --WritePath=/media/nitin/Research/EVDodge/DatasetChethanEvents/Deblurred`

Once you have run the DeblurNet, you can use these outputs to run the HomographyNet if you are using the models with `DB` prefix from [here](https://drive.google.com/drive/u/1/folders/1ZE478rxDKChqD-5KcqUKBOaUa8DT6Qrz).
To run homographynet: Please go to `code\HomographyNetUnsup\`  then run `RunEVHomographyNet.py` with the appropriate command line flags . The command would be:
`RunEVHomographyNet.py --ModelPath=YOURMODELPATH --ReadPath=YOURPATHTOIMGSAFTERDEBLURRING --WritePath=PATHTOSAVEOUTPUTS`

For e.g.,
 `RunEVHomographyNet.py --ModelPath=/media/nitin/Research/EVDodge/CheckpointsDeblurHomographyLR1e-4Epochs400/399model.ckpt --ReadPath=/media/nitin/Research/EVDodge/DatasetChethanEvents/Deblurred --WritePath=/media/nitin/Research/EVDodge/DatasetChethanEvents/DeblurredHomography`


We used the downfacing images in the paper, but found that just using front facing images for homography directly works well if the image is more or less planar (only fails when the moving object is in the image crop used by the network).

[This](https://drive.google.com/file/d/1PIx88W7ED7L49IkHPgooCYwx-VCY8WjL/view) model for homographynet has to be run after using [this](https://drive.google.com/file/d/17fjDy8Y3WduN5fxQI9qYaCSB-LuZBzVv/view?usp=sharing) model for deblurring. 

How do you know which DB model to use? 
Look at the downloaded homography model. It contains a file called `RunCommand.md` which for e.g., looks like this `./TrainEVHomographyNetAllLosses.py --BasePath=/home/nitin/EVDodge/DatasetsForPaper/DownfacingEventsProcessedDBChabM --NumEpochs=200 --NetworkType=Small --CheckPointPath=/home/nitin/EVDodge/prg_evdodge/CheckpointsHomography/ --LogsPath=/media/nitin/Research/EVDodge/LogsHomography/ --GPUDevice=1 --LR=1e-3 --TrainingType=S
` for the above case. Look at the `BasePath`, it says `DBChabM` at the end, this name corresponds with the deblurring model name.

**Comment by NitinJSanket** [comment]
> There is something wrong in the dataset you supplied , because there is no downfacing rosbag .what's more, could you tell me the input and output of deblurnet and homography net.I can not understand the wiki instruction.

Do let me know if you face any more issues.
